### ISSUE TITLE
调整部署，独立计算服务

### ISSUE THREAD

**Issue by zzswang** [catl-spms/devops#1]
sms-ansible 工程，需要调整一下。我看最新的代码应该在 devops 里，拷过来整理一下。

改动：

- 改用 hostpath 来放 uploads 那个目录
- 我增加了一个 yarn job 命令来执行计算，把这个部署成一个独立的服务吧，方便调整replica
- 增加一个 redis

我已经把 avatar 删掉了，在 devops 中也删除吧，减轻负担

**Comment by cc3630** [comment]
已完成
